"""phase_3_rbac_and_tenants

Revision ID: 3ecbda4f9fd1
Revises: c5ce7d2f175c
Create Date: 2026-09-04 03:31:36.408917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ecbda4f9fd1'
down_revision: Union[str, None] = 'c5ce7d2f175c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('slug', sa.String(), nullable=True))
    op.execute("UPDATE organizations SET slug = id WHERE slug IS NULL")
    op.alter_column('organizations', 'slug', nullable=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    
    # Add MANAGER to RoleEnum
    op.execute("ALTER TYPE roleenum ADD VALUE IF NOT EXISTS 'MANAGER'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'full_name')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_column('organizations', 'slug')
    # ### end Alembic commands ###
